---
title: "chipchromatin_step1_peakoverlaps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rtracklayer)
```

## load ChIP peaks - reprocessed Melyssa
```{r}
chip_macs_peaks_dir <- "../data_input/melyssa_zic_data/"
chip_macs_peaks_files <- list.files(chip_macs_peaks_dir,pattern = "bed$")
chip_macs_peaks_full <- paste0(chip_macs_peaks_dir,chip_macs_peaks_files)
chip_macs_peaks_names <- c("P7","NS","P60")

chip_macs_granges <- lapply(chip_macs_peaks_full, import.bedGraph)

names(chip_macs_granges) <- chip_macs_peaks_names

```

## load ChIP peaks 
```{r}
chip_chromatin_peaks_dir <- "../data_output/chip_chromatin/narrowPeak/"
chip_chromatin_peaks_files <- list.files(chip_chromatin_peaks_dir)
chip_chromatin_peaks_full <- paste0(chip_chromatin_peaks_dir,chip_chromatin_peaks_files)
names(chip_chromatin_peaks_full) <- str_split(chip_chromatin_peaks_files,"_",2) %>% map_chr(1)
chip_chromatin_peaks <- map(chip_chromatin_peaks_full, import)

```

Change names
```{r}
reports_tsv <- read_tsv("../execution_scripts/chip_chromatin_sample_info.tsv")

sample_titles <- reports_tsv$sample_title
names(sample_titles) <- reports_tsv$run_accession

names(chip_chromatin_peaks) <- str_replace_all(sample_titles[names(chip_chromatin_peaks)]," ","_")


names(chip_chromatin_peaks) <- str_replace_all(names(chip_chromatin_peaks),"-","_")

write_tsv(reports_tsv,"../data_output/chip_chromatin/chip_sample_info.tsv")
```

## Overlaps
```{r}
get_overlaps_by_element <- function(peaks_a, peaks_b) {
                              intersection1 <- sum(IRanges::overlapsAny(peaks_a,peaks_b))
                              setdiff1 <- length(peaks_a) - intersection1
                              intersection2 <- sum(IRanges::overlapsAny(peaks_b,peaks_a))
                              setdiff2 <-length(peaks_b) - intersection2
                              
                              return(data.frame("intersection1" = intersection1,
                                                "intersection2" = intersection2,
                                                "setdiff1" = setdiff1,
                                                "setdiff2" = setdiff2))}

```


# Get overlaps by element


```{r}

get_peaks_overlaps <- function(chip_macs_granges, peaks){
  peaks_overlaps <- rbind(get_overlaps_by_element(chip_macs_granges$P7, peaks),
                                  get_overlaps_by_element(chip_macs_granges$NS, peaks),
                                  get_overlaps_by_element(chip_macs_granges$P60, peaks))
  
  
  peaks_overlaps$set1 <- c("P7" , "NS", "P60")
  peaks_overlaps$set2 <- c("peaks")
  return(peaks_overlaps)
}

peaks_overlaps_chd7_p4 <- get_peaks_overlaps(chip_macs_granges, chip_chromatin_peaks$P4_ChIP_CHD7_Ctrl_1)

peaks_overlaps_chd7KO_p4 <- get_peaks_overlaps(chip_macs_granges, chip_chromatin_peaks$P4_ChIP_CHD7_cKO)

peaks_overlaps_ctcf_p4 <- get_peaks_overlaps(chip_macs_granges, chip_chromatin_peaks$P4_ChIP_CTCF_Ctrl_1)

peaks_overlaps_chd4_p22 <- get_peaks_overlaps(chip_macs_granges, chip_chromatin_peaks$Chd4_WT_P22_CB1)

peaks_overlaps_chd4KO_p22 <- get_peaks_overlaps(chip_macs_granges, chip_chromatin_peaks$Chd4_cKO_P22_CB1)


peaks_overlaps_list <- list("Chd7 P4" = peaks_overlaps_chd7_p4,
                            "Chd7KO P4" = peaks_overlaps_chd7KO_p4,
                            "CTCF P4" = peaks_overlaps_ctcf_p4,
                            "Chd4 P22" = peaks_overlaps_chd4_p22,
                            "Chd4KO P22" = peaks_overlaps_chd4KO_p22) 
```

# Plot percentages

What percentage of Zic peaks overlap an early CTCF Peak

```{r}
library(tidyverse)

plot_peaks_overlaps <- function(peaks_overlaps){
  peaks_overlaps %>%
    dplyr::select(-setdiff2, -intersection2) %>%
    pivot_longer(where(is.numeric)) %>%
    group_by(set1,set2) %>%
    mutate(percentage = 100 * value / sum(value)) %>%
    ungroup() %>%
    filter(name == "intersection1") %>%
    mutate(set1 = fct_relevel(set1, "P7","NS","P60")) %>%
    ggplot(aes(y = percentage, x = set1, fill = set1)) +
    geom_col(width = 0.5) +
    ylab(NULL) +
    ylab("Percentage") +
    xlab(NULL) +
    theme_light() +
    theme(aspect.ratio = 1.5,legend.title = element_blank()) +
    ylim(c(0,100)) +
    scale_fill_manual(values = c("P7"="blue","NS"="gray","P60"="red"))
}

```

```{r}
imap(peaks_overlaps_list, ~ plot_peaks_overlaps(.x) + ggtitle(.y))
```
Plot everything
```{r}

chip_chromatin_peaks_olaps <- map(chip_chromatin_peaks, get_peaks_overlaps,chip_macs_granges = chip_macs_granges )
```

```{r}

imap(chip_chromatin_peaks_olaps, ~ plot_peaks_overlaps(.x) + ggtitle(.y))

```

# Add anchor information
```{r}
mapped_data <- read_tsv("../data_input/melyssa_zic_data/mapped_data.txt")
chip_macs_granges


```
```{r}
mapped_data_in_anchors <- mapped_data %>% 
  dplyr::filter(!is.na(id)) %>% 
  dplyr::filter(!is.na(zic_peak)) %>%
  # extract chr, start, end
  dplyr::mutate(chr = str_extract(zic_peak,"[^\\:]+"), 
  start = str_extract(zic_peak, "(?<=:).+(?=-)") , 
  end = str_extract(zic_peak, "\\b\\w+$")) %>%
  select(chr, start, end, zic_sig, gene_sig) %>%
  distinct()
  
```

```{r}
mapped_data_in_anchors$start <- as.numeric(mapped_data_in_anchors$start)
mapped_data_in_anchors$end <- as.numeric(mapped_data_in_anchors$end)

mapped_data_in_anchors_gr <- makeGRangesFromDataFrame(mapped_data_in_anchors,
                         keep.extra.columns = TRUE)

mapped_data_in_anchors_gr_zic_sig_list <- split(mapped_data_in_anchors_gr,mapped_data_in_anchors_gr$zic_sig)

mapped_data_in_anchors_gr_zic_gene_sig_list <- split(mapped_data_in_anchors_gr,paste0(mapped_data_in_anchors_gr$zic_sig,mapped_data_in_anchors_gr$gene_sig ))

mapped_data_in_anchors_gr_zic_gene_sig_list_anti <- mapped_data_in_anchors_gr_zic_gene_sig_list[c("DOWNUP","N.S.N.S.","UPDOWN")]

mapped_data_in_anchors_gr_zic_gene_sig_list <- mapped_data_in_anchors_gr_zic_gene_sig_list[c("DOWNDOWN","N.S.N.S.","UPUP")]

```

```{r}
names(mapped_data_in_anchors_gr_zic_sig_list) <- c("P7","NS","P60")
names(mapped_data_in_anchors_gr_zic_gene_sig_list) <- c("P7","NS","P60")

```



```{r}

chip_chromatin_peaks_olaps_anchors <- map(chip_chromatin_peaks, get_peaks_overlaps,chip_macs_granges = mapped_data_in_anchors_gr_zic_sig_list)


imap(chip_chromatin_peaks_olaps_anchors, ~ plot_peaks_overlaps(.x) + ggtitle(.y))

```

```{r}
chip_chromatin_peaks_olaps_anchors <- map(chip_chromatin_peaks, get_peaks_overlaps,chip_macs_granges = mapped_data_in_anchors_gr_zic_gene_sig_list)


imap(chip_chromatin_peaks_olaps_anchors, ~ plot_peaks_overlaps(.x) + ggtitle(.y))

```

```{r}
names(mapped_data_in_anchors_gr_zic_gene_sig_list_anti) <- c("P7","NS","P60")

chip_chromatin_peaks_olaps_anchors <- map(chip_chromatin_peaks, get_peaks_overlaps,chip_macs_granges = mapped_data_in_anchors_gr_zic_gene_sig_list_anti)


imap(chip_chromatin_peaks_olaps_anchors, ~ plot_peaks_overlaps(.x) + ggtitle(.y))

```
Notes:
- At least a subset of late Zic binding is concomitant with Chd4.
- Many late Zic peaks also overlap early Chd7, 
